### ISSUE TITLE
Renamed Gramps?

### ISSUE THREAD

**Issue by eno93** [GenealogyCollective/gprime#1]

**Comment by dsblank** [comment]
Unfortunately, it is a fork. See https://groups.google.com/forum/#!forum/genealogycollective for discussion group.

**Comment by dsblank** [comment]
I see that you are making copies of all of the github genealogy programs. Gprime will be different from Gramps. It will use a SQL database backend, and will use different technologies going forward. What used to be called "gramps-connect" (a server-based program) will be developed under gprime. First release of gprime will probably be in Nov 2016.

**Comment by uxcq** [comment]
So what happens to the current [Gramps-connect](https://github.com/gramps-project/gramps_connect) is it deprecated, are the changes @Nick-Hall is making going to stop it from working?

Found this via reddit by the way
https://www.reddit.com/r/gramps/comments/5879zl/fork_gprime_incorporating_grampsconnect/

**Comment by uxcq** [comment]
Answered on reddit by @dsblank :

> 
> Further information on the developers mailing list:
> 
> http://gramps.1791082.n4.nabble.com/Gprime-td4677195.html
> 
> The goal will be to make a better, faster, more stable genealogy program. Is that friendly? It will continue to support the Gramps XML import/export.
> 

> 
> I said "unfortunately" because I really didn't want to fork gramps... I'd always rather work with a group (especially when with a group I have been working with for over 10 years). But, because of differences of vision, I decided that it wasn't viable.
> 
> I'm not too happy with the name of the group nor project name, but just picked those to start with. Suggestions welcome!
>

**Comment by enlite93** [comment]
Cool, more the merrier.

@dsblank should probably contact the developer of the other fork called [GrampsCollaborate](http://www.grampscollaborate.org/) 

> What is GrampsCollaborate?
> 
> GrampsCollaborate is a user-based, dynamic website designed to compliment Gramps Genealogical Research Software. I designed it primarily to fulfill my own needs which are specifically:
> 
>     I want to use Gramps (desktop) as my primary research program
>     I wanted to share my research with other family members via a website
>     I wanted to protect the privacy of individuals in my tree by relationship
>     I wanted to protect the privacy of sensitive information and records, even from close relatives
>     I wanted family members to be able to contribute information, corrections and documents
> 
> Gramps is an excellent, full-featured research tool and it is not inherently collaborative. That suits me fine; I'm a bit of a control freak with an academic background so nothing goes into my tree unless it's properly sourced and I put it there. That said, I certainly want to share my research. You can export gramps to a static website—which is great, and I did do that for a while—but that starts to raise privacy concerns. Even if you, say, password protect that site, any tree of appreciable size will contain information that shouldn't be readily available to even other people in that tree. A static export is simply not sufficient.
> 
> Furthermore, anyone who has done any genealogical research knows that the task never ends. Every family member has more pieces to the puzzle, and a static webpage doesn't make it easy for them to contribute or correct facts.
> 
> There are lots of full-featured, collaborative tools online for genealogical research, even for Gramps—see Gramps-Connect. These, however, are designed to be the primary research tool and for collaboration between researchers that are genuinely working together rather than a single researcher disseminating information and gathering feedback and other sources. Additionally, I have not encountered software that restricts what information is viewable by users who already have access to the site (I'm happy to hear about any that do).
> 
> GrampsCollaborate is therefore somewhere in between a static webpage and a tool that you would use to create your family tree and has a multi-faceted approach to protecting personal information. Specifically GrampsCollaborate:
> 
>     is based on the Gramps Narrated Website report - Basic-Ash
>     uses an exported Gramps XML file
>     has one owner/administrator who can upload databases, media files, manage users and view all records
>     by default allows users to view all non-private details of deceased people and living people that they (or their spouse) shares a common ancestor with
>     invited users have these permissions controls
>         View Living (if 'yes', user can see all individuals and non-private details; if 'no', user can see last names only and no details)
>         View Relatives ('View Living' must be 'no'; if 'yes', user can see all individuals that share a common ancestor with themself or their spouse and their non-private details)
>         View Privates (if 'yes', user can see private details of individuals viewable according to the previous two permissions)
>         Invite Others (if 'yes', user can invite other living individuals to join the site by supplying an e-mail address)
>     allows users to add people, facts, comments and documents that the owner can than integrate into the tree at their discretion
> 
> GrampsCollaborate is in an alpha state and is a project that I only work on in my free time so no promises or guarantees. That said, if you would like to try out the site for yourself and provide me some feedback or would just like more information about this project, you can contact me at sean@grampscollaborate.org

**Comment by eno93** [comment]
Thanks for the explanationetc...

As per @dsblank discussion can happen on https://groups.google.com/forum/#!forum/genealogycollective  if interested?
