### ISSUE TITLE
hard to shut down server

### ISSUE THREAD

**Issue by bpisoj** [GenealogyCollective/gprime#2]
In Windows it is hard to shut down tornado server (v4.2.2)
Attached quick patch modeled after:
http://stackoverflow.com/questions/17101502/how-to-stop-the-tornado-web-server-with-ctrlc
There is also explanation why is not working on Windows currently.
[app.patch.txt](https://github.com/GenealogyCollective/gprime/files/612359/app.patch.txt)

**Comment by dsblank** [comment]
Thanks for reporting!

Please try d4a69cd

**Comment by dsblank** [comment]
Also fixed the crypt issue. New requirement, passlib. Verified that gPrime now works on Windows.

**Comment by bpisoj** [comment]
@v4-fdf1196
Nice to have it automatically open in default browser!
Issue with shutting tornado server is fixed!
With passlib (did not fully check) two issues of three from:
http://gramps.1791082.n4.nabble.com/Announcing-gPrime-tt4677747.html#a4677762
is solved.

What about third one gprime create database in current working folder and can't access it latter?
In app.py "DbState().create_database(options.create)" call function as database name as parameter,
in dbstate.py "create_database(self, dirpath, name="Untitled Family Tree")" create folder "dirpath" when it should create "home-dir"/"database name"
Looks to me as first function do not use right parameters.

**Comment by dsblank** [comment]
I'm still wrestling with the best way to have gPrime deal with databases. Going forward, I'm thinking that this will only support one type (DBAPI) and not sure if the user will need to have more than one database at a time. I think you are right... I don't like this current system though. Still thinking this part through...

So, for now, I think the windows issues are solved.
