### ISSUE TITLE
Not handling "--pasword" command line argument

### ISSUE THREAD

**Issue by bpisoj** [GenealogyCollective/gprime#3]
Passlib works but no to handling command line argument password

[crypt.patch.txt](https://github.com/GenealogyCollective/gprime/files/613698/crypt.patch.txt)

`

**Comment by dsblank** [comment]
I'm not sure we want to do that as it allows/encourages people to put the actual password on the command line. The way that it currently works is that you can pass a hash of the password.

**Comment by bpisoj** [comment]
I understand now, can you then make explanation like that in usage options ("--help")
For dummies like me can you also catch such error of using plaintext in password and handle them nicely with explanation what is wrong instead of that confusing "ValueError: not a valid sha256_crypt hash" tracebak.

Is it possible to make error page in browser prettier, something more in style with rest of gprime.
Error page is so minimalistic that i always have feeling that hole browser is crashed.

**Comment by dsblank** [comment]
Started #4 to track missing error page.
